# [PYIA-A04] Crie uma função chamada media que receberá três números como argumentos. Esta função deve calcular a média aritmética desses três números. Para fazer isso, some os três números e, em seguida, divida o resultado por três. Por fim, a função deve retornar o valor da média aritmética calculada.

def media(a, b, c):
    resultado = (a + b + c) / 3
    return resultado

#SE FOR EXECUTAR, SEGUE EXEMPLO DE UMA EXECUÇÃO DA FUNÇÃO:
# resultado_media = media(10, 20, 30)
# print(f"A média é: {resultado_media}")
